### ISSUE TITLE
3.2.0 -> 3.3.0 broke semver

### ISSUE THREAD

**Issue by budziq** [Geal/rust-syslog#24]
Hi,

Transition to 3.3.0 broke semver due to following commit https://github.com/Geal/rust-syslog/commit/03a7779f2968d25a246f5c62e271c37bec5787f0 causing buildbreak in our [nightly travis](https://travis-ci.org/rust-lang-nursery/rust-cookbook/builds/266625931)

No biggie, you can close this issue right away. Just wanted to let you know :smile:

**Comment by Geal** [comment]
oh, right, sorry :(
Note that version 4.0 will break a lot of things in the API, but this time respecting semver

**Comment by budziq** [comment]
No problem :)
