### ISSUE TITLE
Support Log 0.4

### ISSUE THREAD

**Issue by mssun** [Geal/rust-syslog#32]
The Log crate (https://crates.io/crates/log) is 0.4.1 now. However `rust-syslog` does not support the newer version. I found that are some naming changes for 0.4. (e.g., `LogLevel` -> `Log`). Therefore I cannot use syslog follow the instruction from the Rust Cook Book: https://rust-lang-nursery.github.io/rust-cookbook/logging.html#ex-log-syslog

**Comment by daboross** [comment]
It's worth noting that even without official support from `syslog`, its possible to shim support into a log-0.4-based logging library. This is what `fern` does while we wait for an update to the crate.

**Comment by daboross** [comment]
Hm- I'm not too familiar with `error-chain` either, but I think something like this should work:

```diff
@@ -272,15 +276,14 @@ pub fn init_unix_custom<P: AsRef<Path>>(facility: Facility, log_level: log::LogL
     pid:      pid,
   };
   unix_custom(formatter, path).and_then(|logger| {
-    log::set_logger(|max_level| {
-      max_level.set(log_level);
-      Box::new(BasicLogger::new(logger))
-    }).chain_err(|| ErrorKind::Initialization)
+    log::set_boxed_logger(Box::new(BasicLogger::new(logger))).chain_err(|| ErrorKind::Initialization)?
+
+    log::set_max_level(log_level);
+
+    Ok(())
   })
 }
```

Is the source of your error trying to use `log::set_logger`, possibly? log 0.4 changed what used to be `set_logger` into the `set_boxed_logger` function. `set_logger` is really only useful in static situations now.

**Comment by mssun** [comment]
I don't know the difference of`log::set_logger` and `log::set_boxed_logger`, but I can compile with `log::set_logger` function. Anyway, I think it's easy to support 0.4 right now.

**Comment by Geal** [comment]
syslog now uses log 0.4
