### ISSUE TITLE
Formatter*::pid takes i32, but std::process::id returns u32

### ISSUE THREAD

**Issue by jac-leadnav** [Geal/rust-syslog#46]
All,

In order to run properly, I must do the following:

```
    /* get our process id (syslog takes i32, but we get u32) */
    let p = process::id();
    let pid = if p > std::i32::MAX as u32 {
        0
    } else {
        p as i32
    };

    /* format for our syslog messages */
    let formatter = Formatter3164 {
        facility: Facility::LOG_USER,
        hostname: None,
        process: "myrustprocess".into(),
        pid: pid,
    };
```

If we could change the type of `pid` to be `u32`, then we wouldn't have to jump through the overflow check...

I've checked and both `Formatter*` structs are `i32` for `pid`

Thanks!

Jason

**Comment by carnott-snap** [comment]
It looks like internally `syslog` uses `libc::getpid` not `std::process::id`, [`syslog::get_process_info`](https://github.com/Geal/rust-syslog/blob/92a087169743699c489d6a5fd5c857017862b59a/src/lib.rs#L462), and that is the source of the i32.

It would be a breaking change to fix this, and there may be good reason to use `libc` over `std`, but I cannot conceive of it, thus would appreciate a new major version to make this more ergonomic.
