### ISSUE TITLE
How to set the log to respect log-specification?

### ISSUE THREAD

**Issue by abclmnoxyz** [Geal/rust-syslog#58]
Great lib, thanks.

I have a problem when using the lib:
It can only set log-level and does not follow log-specification.

For example:
I want to show my_app's all debug log, but all others are in info-level:
> RUST_LOG=info;my_app=debug

Is there a way to implement this? Thanks very much!

**Comment by Geal** [comment]
this is best done at another level of your logging system. This crate is there mainly as output
