### ISSUE TITLE
EPROTOTYPE is not constant between platforms

### ISSUE THREAD

**Issue by oherrala** [Geal/rust-syslog#59]
In the commit 01625ab131323e8df79d306d5a97d33045f97817 a dependency to `libc` crate was removed and `EPROTOTYPE` was hard coded as constant with value 91. However, this is not portable between platforms.

Quick grep over `libc` crate's source code reveals that `EPROTOTYPE` can be (this is not definitive list):

 * 98 in Linux running on MIPS (both 32bit and 64bit)
 * 41 in Linux running on SPARK  (both 32bit and 64bit)
 * 41 is also used in Apple, and FreeBSD, NetBSD and OpenBSD
 * 98 in Solaris

**Comment by Geal** [comment]
damn, I thought I had checked for that. damn I thought I had checked for that. This is fixed in 6.0.1
