### ISSUE TITLE
Where is version 6.0.0?

### ISSUE THREAD

**Issue by nyuichi** [Geal/rust-syslog#61]
syslog 6.0.0 was released at https://crates.io/crates/syslog last week but I was unable to find the source for it here.
Perhaps you might just have forgot to push new commits to github, or am I missing something? Thanks.

**Comment by jamacku** [comment]
@Geal It would be nice to have a `6.0.0` tag, so packagers could update distribution packages. I'm struggling to build by package for Fedora against `syslog 6.0.0`. Thank you.

Also README seems to be outdated, compared against [crates.io](https://crates.io/crates/syslog)

**Comment by Geal** [comment]
I forgot to push it, sorry, this is fixed now
