### ISSUE TITLE
issues on sending logs to tcp

### ISSUE THREAD

**Issue by sify21** [Geal/rust-syslog#63]
1. can't integrate with the `log` crate when using tcp (unix is ok).

I debugged this by starting rsyslog with `rsyslogd -dn`, the output shows imtcp accepted the connection, but no log entry is added. I suspect that logs are not sent when using `info!` from `log` crate.

2. when using `logger.info(...)`, must manually add '\n' at the end of every message.
3. time is not local

**Comment by franklx** [comment]
Same issue here.
TCP connection with syslog server is established and disconnected on cleanup (checked it with tcpdump) but nothing is sent by log::{info, error, debug} functions.
Even the UDP backend doesn't send anything at all.

**Comment by Roguelazer** [comment]
See #70 for a proposed fix

**Comment by Geal** [comment]
fixed by #70
